name: HomeMoneyEnterprise CI
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
jobs:
  predeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 16.17.0
        uses: actions/setup-node@v2
        with:
          node-version: '16.17.0'
      - run: npm install
